# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0004_loggeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.AddField(
            model_name='loggeduser',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ttt.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='vs_comp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='vs_player',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
