# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0006_remove_loggeduser_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_size', models.PositiveIntegerField(default=3)),
                ('game_lenght', models.PositiveIntegerField(default=3)),
                ('score', models.CharField(max_length=7)),
                ('challenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='ttt.Player')),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='ttt.Player')),
            ],
        ),
    ]
