# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 07:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0008_auto_20160329_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1, message='Your name must consist of at least 1 character.')]),
        ),
    ]
