# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0009_auto_20160401_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='challenger',
        ),
        migrations.RemoveField(
            model_name='score',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='loses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.ForeignKey(default='hrac', on_delete=django.db.models.deletion.CASCADE, to='ttt.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
