# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0010_auto_20160414_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='board_size',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='score',
            name='game_lenght',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
