# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0015_auto_20160416_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='_loses',
            field=models.PositiveIntegerField(db_column='loses', default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='_wins',
            field=models.PositiveIntegerField(db_column='wins', default=0),
        ),
    ]
